export const options = [
  "100",
  "13th",
  "13th Age",
  "Abstraktní",
  "akční",
  "Alternativní historie",
  "Amazonie",
  "ame",
  "amer",
  "amer**",
  "ameritrash",
  "Andělé a démoni",
  "Apocalypse World",
  "Argumentační",
  "Asterion",
  "Atmosférický",
  "awesomeness:5",
  "Aye Dark Overlord",
  "Běhací",
  "Bez systému",
  "Bez vypravěče",
  "Blades in the Dark",
  "Blázinec",
  "Bliss Stage",
  "Capes Superhero",
  "Card Driven Storytelling",
  "Cthuhu Mythos",
  "Cthulhu Mythos",
  "Cyberpunk",
  "Časová smyčka",
  "Časy se mění",
  "Čína",
  "D&D 4e",
  "D&D 5e",
  "Dakara",
  "Dark Fantasy",
  "Das schwarze Auge",
  "Das schwarze Auge 5e",
  "Debata",
  "deckbuilding",
  "deluxe",
  "Demohraní",
  "Derry",
  "deskofobie",
  "deskové hry",
  "Detektivní",
  "Divoký západ",
  "DnD 4e",
  "DnD 4e Lair assault",
  "Dnd 5",
  "DnD 5e",
  "DnD5e klon",
  "dobrodružná",
  "Dobrodružné",
  "Dobrodružný",
  "Dogs in the Vineyard",
  "Dračák",
  "Dračák podle staré školy",
  "Dračí doupě",
  "Dračí doupě 1.0",
  "Dračí doupě 1.6",
  "Dračí kutloch",
  "Drama",
  "DrD",
  "DrD 1.6",
  "DrD 1.x",
  "DrD II",
  "DrD II Mistři",
  "DrD+",
  "DrDII",
  "DrDII Mistři",
  "DrDo",
  "Dread",
  "Dread!",
  "Dreadfleet",
  "Dungeon World",
  "Dungeoncrawl",
  "edukativní",
  "ekonomická",
  "End of the World",
  "Eng Only",
  "Engel",
  "English",
  "euro",
  "eurovka",
  "Exalted",
  "ezměte si figurku a stvořte si vlastního drsňáka nebo bojové mon",
  "FAE",
  "Fall of Delta Green",
  "Fantasy",
  "Fantasy/Sci-Fi",
  "FATE",
  "Fate 3e Core",
  "Fate 4e",
  "Fate 4e Core",
  "Fiasco",
  "Forgotten Realms",
  "Francie",
  "free",
  "gamebook",
  "GUMSHOE",
  "GURPS",
  "GURPS 4e",
  "HELP",
  "Herní styl: akooperativní",
  "Herní styl: Ameritrash",
  "Herní styl: Atmosférická",
  "Herní styl: Atmosférický",
  "Herní styl: Běhací",
  "Herní styl: Deckbuilding",
  "Herní styl: Dungeoncrawl",
  "Herní styl: Ekonomická",
  "Herní styl: Euro",
  "Herní styl: Hádanky",
  "Herní styl: Kooperativní",
  "Herní styl: Odlehčený",
  "Herní styl: Odpočinková",
  "Herní styl: Oldschool",
  "Herní styl: Párty hra",
  "Herní styl: Přemýšlecí",
  "Herní styl: Semi-kooperativní",
  "Herní styl: Strategická",
  "Herní styl: Týmová",
  "Herní styl: Učící",
  "Herní styl: Vážný",
  "Herní styl: Vyjednávací",
  "Herní styl: Vyprávěcí",
  "Herní styl: Wargame",
  "Herní styl: Worker Placement",
  "High Fantasy",
  "Historický",
  "historie",
  "Hlídka",
  "Horor",
  "hrdý i děsivý život",
  "Hunter: the Vigil",
  "Chuubo's Marvelous Wish Granting Engine",
  "i pro",
  "i pro nováčky",
  "Improvizační",
  "Itálie",
  "Jeep",
  "jeepforma",
  "Kensington",
  "Komediální",
  "komedie",
  "Končina",
  "Konstantinopol",
  "kooperativní",
  "kostýmová",
  "Kostýmový",
  "KoW",
  "Labyrinth Lord",
  "Legendary Tales",
  "Legendy",
  "Londýn",
  "Low Fantasy",
  "Mage tA",
  "Malajsie",
  "Malifaux",
  "Mexiko",
  "MG",
  "Microscope",
  "mocný",
  "Mouse Guard",
  "Muzikál",
  "My Little Pony",
  "Mysteriózní",
  "Nanking",
  "Nepravidlová",
  "New weird",
  "Night's black agents",
  "Night?s Black Agents",
  "noir",
  "Norsko",
  "Numenéra",
  "Obchod",
  "Odlehčená",
  "Odlehčený",
  "Odpočinková",
  "Og",
  "Old School",
  "Oldschool",
  "Pán prstenů",
  "Paranoia XP",
  "Párty hra",
  "Pathfinder",
  "Pendragon",
  "Penny for my thoughts",
  "Piráti",
  "Playtest",
  "Polaris",
  "Post-apo",
  "Postapokalyptická",
  "Praha",
  "Pravidlová",
  "Prime Time Adventures",
  "Primetime Adventures",
  "pro pokročilé",
  "Prostředí: Cthuhu Mythos",
  "Prostředí: Postapokalyptické",
  "Prostředí: Současnost",
  "Prostředí: Star Wars",
  "Prostředí: Tropické",
  "Prostředí: Vesmír",
  "přednáška",
  "Přemýšlecí",
  "Příběhy imp.",
  "Příběhy Impéria",
  "Psychologická",
  "Pulp",
  "Realita",
  "Renaissance Deluxe",
  "Risus",
  "Rogue Trader",
  "Romance",
  "rovníková Afrika",
  "RPG",
  "Saga",
  "Sci-fi",
  "Science-fantasy",
  "semi",
  "semi-kooperativní",
  "Shadow of the Demon Lord",
  "Shadowrun",
  "Shadowrun II. Edice",
  "shadows",
  "Shadows of Esteren",
  "Sibiř",
  "Singapur",
  "Skriptovaný",
  "Sny",
  "Sociální drama",
  "Solar",
  "Současnost",
  "Space opera",
  "Star Wars",
  "Star Wars Saga Edition (d20)",
  "steampunk",
  "Storyteller /WoD system",
  "strategická",
  "Strepy snu",
  "střepy snů",
  "Stříbrná hlídka",
  "Superhrdinové",
  "Svět Dračáku / Powered by the Apocalypse",
  "Symbaroum",
  "Systém: Apocalypse World",
  "Systém: Aye Dark Overlord",
  "Systém: Časy se mění",
  "Systém: Das schwarze Auge 5e",
  "Systém: DrD 1.6",
  "Systém: DrD+",
  "Systém: End of the World",
  "Systém: FAE",
  "Systém: Fate 4e",
  "Systém: Fiasco",
  "Systém: Labyrint Lord",
  "Systém: Labyrinth Lord",
  "Systém: Microscope",
  "Systém: Mouse Guard",
  "Systém: Numenéra",
  "Systém: Polaris",
  "Systém: Risus",
  "Systém: Solar",
  "Systém: Ten Candles",
  "Tails of Equestria",
  "taneční",
  "Taria",
  "Tasmánie",
  "Taškent",
  "Temné",
  "Ten candles",
  "The one Ring",
  "The Sprawl",
  "Through the breach",
  "Tibet",
  "Tragédie",
  "Turnaj",
  "Turnaj Párty hra",
  "Týmová",
  "Učící",
  "Urbanfantasy",
  "válečná",
  "Vážná",
  "Vážný",
  "Věk 15+",
  "Věk 6+",
  "Věk 8+",
  "věk:",
  "Věk: 10+",
  "Věk: 12+",
  "Věk: 14+",
  "Věk: 15+",
  "Věk: 18+",
  "Věk: 8+",
  "Věk: 9+",
  "Venkovní",
  "Viktoriánská doba",
  "vyjednávací",
  "vyprávěcí",
  "vznešený",
  "Vztahová",
  "Vztahový",
  "wargame",
  "Wargaming",
  "Warhammer 40",
  "Warhammer 40k",
  "Warhammer Fantasy Battle",
  "Warhammer Fantasy Roleplay",
  "warzone",
  "Western",
  "WFR 2e",
  "WFRP 3e",
  "WH40: DH",
  "WH40K",
  "WHFB",
  "WoD",
  "worker placement",
  "workshop",
  "World of Darkness",
  "World of Darkness 5e",
  "Žánr: Akční",
  "Žánr: Alternativní historie",
  "Žánr: Cyberpunk",
  "Žánr: Dark Fantasy",
  "Žánr: Detektivní",
  "Žánr: Dobrodružný",
  "Žánr: Fantasy",
  "Žánr: Historický",
  "Žánr: History fiction",
  "Žánr: Horor",
  "Žánr: Komediální",
  "Žánr: Mysteriózní",
  "Žánr: Post-apo",
  "Žánr: Romance",
  "Žánr: Sci-fi",
  "Žánr: Science-fantasy",
  "Žánr: Space Opera",
  "Žánr: Steampunk",
  "Žánr: Tragédie",
  "Žánr: Urbanfantasy",
  "Žánr: Western",
  "žánrovka"];
